export const state = {
    geojsonData: null,
    contourLines: [],
    redPoints: [],
    bounds: { minX: Infinity, maxX: -Infinity, minY: Infinity, maxY: -Infinity },
    elevationRange: { min: Infinity, max: -Infinity },
    coordinateScale: 1,
    coordinateOffsetX: 0,
    coordinateOffsetY: 0,
    navigation: {
        zoom: 1,
        offsetX: 0,
        offsetY: 0,
        isDragging: false,
        lastMouseX: 0,
        lastMouseY: 0,
    },
    visual: {
        rotation: 0,
        lineWeight: 2,
        smoothness: 0,
        density: 1,
        pointSize: 10,
        useElevationColors: true,
    },
    crop: {
        mode: false,
        hoveredLineIndex: -1,
        hoveredElevationIndex: -1,
        mouseCanvasX: 0,
        mouseCanvasY: 0,
    },
    delete: {
        mode: false,
        hoveredLineIndex: -1,
        hoveredElevationIndex: -1,
        mouseCanvasX: 0,
        mouseCanvasY: 0,
    },
    canvas: {
        width: 800,
        height: 800,
    },
};
